spring.application.name=cyclix-api
server.port=6060
spring.docker.compose.file=docker-compose.yaml
spring.flyway.validate-migration-naming=true
app.jwt.secret=cyclix-local-dev-secret-change-me-please-123456
app.jwt.expiration-seconds=86400
app.device.api-key=cyclix-esp32-local-key-change-me
app.device.location.audit.active.min-distance-meters=15.0
app.device.location.audit.active.max-seconds-between-points=10
app.device.location.audit.idle.min-distance-meters=30.0
app.device.location.audit.idle.max-seconds-between-points=60
